### ISSUE TITLE
error  401

### ISSUE THREAD

**Issue by wuxin-hun** [recitativonika/teneo-account-creator#3]
const response = await axios.post(regurl, {
    email: email,
    password: password,
    data: { invited_by: 'some_referral_code' },
    gotrue_meta_security: {},
    code_challenge: null,
    code_challenge_method: null,
}, axiosConfig);

error and i degug to display more info but i do not konw what happened

<img width="1010" alt="image" src="https://github.com/user-attachments/assets/20e54fa9-177b-4175-9f1b-58157eed29a0">

**Comment by recitativonika** [comment]
can you send me an error from the console when you run the script, not the debug?

**Comment by seekitx** [comment]
of course！

**Comment by seekitx** [comment]
<img width="522" alt="image" src="https://github.com/user-attachments/assets/bcb6abe4-e7f1-4778-b596-40fa2f80f2a4">

**Comment by recitativonika** [comment]
Do you already set proxy in `email.txt`? Seems like in your console it show localhost address

**Comment by recitativonika** [comment]
![image](https://github.com/user-attachments/assets/6cb275f5-4404-4691-a73a-5105b1ce6d29)
if you put correctly, it should work. I tested it and it still work.
